version: '3.8'

services:
  postgres:
    image: postgres:17.2
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"